<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <PackageId>Posta</PackageId>
    <AssemblyName>Posta</AssemblyName>
    <RootNamespace>Posta</RootNamespace>
    <Version>0.1.0</Version>
    <Title>Posta .NET SDK</Title>
    <Description>The .NET SDK for the Posta self-hosted email delivery platform.</Description>
    <Authors>Posta</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://docs.goposta.dev/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/goposta/posta-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>posta email sdk api client</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <Compile Remove="Posta.Aspire\**\*.cs" />
    <Compile Remove="Posta.Tests\**\*.cs" />
    <None Remove="Posta.Aspire\**\*" />
    <None Remove="Posta.Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Posta.Tests" />
    <InternalsVisibleTo Include="Posta.Aspire" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
  </ItemGroup>

</Project>
